name = "mygov-click-counter"
main = "worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "CLICK_KV"
id = "这里粘贴KV_ID"
